### PR TITLE
add client-id

### PR DESCRIPTION
**Pull request by Marc-Morata-Fite**

### CODE REVIEW

**Comment by ZimbiX** [comment]
Already patched in my fork: https://github.com/ZimbiX/Twitch-Video-Download-Tools

**Comment by Marc-Morata-Fite** [comment]
I do not see a PR with the patch.

**Comment by ZimbiX** [comment]
There was no PR; I patched it myself. [Note the second-last commit message](https://github.com/ZimbiX/Twitch-Video-Download-Tools/commits/master)

**Comment by abronte** [comment]
Need this merged or no?

**Comment by Marc-Morata-Fite** [comment]
Needs to be merged to fix it.

**Pull request merged**
